# Generated by Django 3.1.7 on 2022-02-16 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db', models.CharField(max_length=100)),
                ('ticker', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('open', models.DecimalField(decimal_places=3, max_digits=5)),
                ('high', models.DecimalField(decimal_places=3, max_digits=5)),
                ('low', models.DecimalField(decimal_places=3, max_digits=5)),
                ('adj_close', models.DecimalField(decimal_places=3, max_digits=5)),
                ('rownumber', models.DecimalField(decimal_places=3, max_digits=5)),
                ('short_ema', models.DecimalField(decimal_places=3, max_digits=5)),
                ('medium_ema', models.DecimalField(decimal_places=3, max_digits=5)),
                ('long_ema', models.DecimalField(decimal_places=3, max_digits=5)),
                ('positive_directional_index_indicator', models.DecimalField(decimal_places=3, max_digits=5)),
                ('negative_directional_index_indicator', models.DecimalField(decimal_places=3, max_digits=5)),
                ('adx_indicator', models.DecimalField(decimal_places=3, max_digits=5)),
                ('suport_line', models.DecimalField(decimal_places=3, max_digits=5)),
                ('resistance_line', models.DecimalField(decimal_places=3, max_digits=5)),
                ('max_axis', models.DecimalField(decimal_places=3, max_digits=5)),
                ('min_axis', models.DecimalField(decimal_places=3, max_digits=5)),
                ('trigger_field1', models.CharField(max_length=1000)),
                ('trigger_field3', models.CharField(max_length=1000)),
                ('trigger_field4', models.CharField(max_length=1000)),
                ('trigger_field5', models.CharField(max_length=1000)),
                ('trigger_field6', models.CharField(max_length=1000)),
                ('atr', models.DecimalField(decimal_places=3, max_digits=5)),
                ('floatshort', models.DecimalField(decimal_places=3, max_digits=5)),
                ('company', models.CharField(max_length=300)),
                ('earnings_date', models.CharField(max_length=15)),
                ('call_time', models.CharField(max_length=100)),
                ('estimate_eps', models.DecimalField(decimal_places=3, max_digits=5)),
                ('zero_line', models.DecimalField(decimal_places=3, max_digits=5)),
                ('twenty_five_line', models.DecimalField(decimal_places=3, max_digits=5)),
                ('forty_line', models.DecimalField(decimal_places=3, max_digits=5)),
                ('max_avg_upper', models.DecimalField(decimal_places=3, max_digits=5)),
                ('min_avg_low', models.DecimalField(decimal_places=3, max_digits=5)),
                ('name', models.CharField(max_length=300)),
                ('industry', models.CharField(max_length=300)),
                ('vol_spike_bar', models.DecimalField(decimal_places=3, max_digits=5)),
            ],
        ),
    ]
