# Generated by Django 3.1.7 on 2022-02-16 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alloptionplay', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='trigger_field2',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='call_time',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='company',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='date',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='db',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='earnings_date',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='industry',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='name',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='ticker',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='trigger_field1',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='trigger_field3',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='trigger_field4',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='trigger_field5',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='trigger_field6',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
