# Generated by Django 3.1.7 on 2022-02-18 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alloptionplay', '0005_auto_20220216_2324'),
    ]

    operations = [
        migrations.RenameField(
            model_name='info',
            old_name='atr',
            new_name='bottom_value',
        ),
        migrations.RenameField(
            model_name='info',
            old_name='call_time',
            new_name='country_ticker_pk',
        ),
        migrations.RenameField(
            model_name='info',
            old_name='company',
            new_name='demandline_high',
        ),
        migrations.RenameField(
            model_name='info',
            old_name='earnings_date',
            new_name='demandline_low',
        ),
        migrations.RenameField(
            model_name='info',
            old_name='estimate_eps',
            new_name='mov_100day_adj_close',
        ),
        migrations.RenameField(
            model_name='info',
            old_name='floatshort',
            new_name='mov_200day_adj_close',
        ),
        migrations.RenameField(
            model_name='info',
            old_name='industry',
            new_name='mov_8day_adj_close',
        ),
        migrations.RenameField(
            model_name='info',
            old_name='name',
            new_name='neg_forty_line',
        ),
        migrations.RenameField(
            model_name='info',
            old_name='vol_spike_bar',
            new_name='neg_twenty_five_line',
        ),
        migrations.AddField(
            model_name='info',
            name='supplyline_high',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='supplyline_low',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='top_value',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='trigger_field7',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='vwap',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
