# Generated by Django 3.1.7 on 2022-02-26 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alloptionplay', '0007_data'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='data',
            index=models.Index(fields=['strategy'], name='alloptionpl_strateg_33ab22_idx'),
        ),
        migrations.AddIndex(
            model_name='data',
            index=models.Index(fields=['list_date'], name='alloptionpl_list_da_f57ddc_idx'),
        ),
        migrations.AddIndex(
            model_name='info',
            index=models.Index(fields=['ticker'], name='alloptionpl_ticker_ad6dbf_idx'),
        ),
        migrations.AddIndex(
            model_name='info',
            index=models.Index(fields=['date'], name='alloptionpl_date_3fa575_idx'),
        ),
    ]
