# Generated by Django 3.1.7 on 2022-02-27 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alloptionplay', '0008_auto_20220226_2250'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='data',
            index=models.Index(fields=['ticker'], name='alloptionpl_ticker_3f3c98_idx'),
        ),
    ]
