# Generated by Django 3.1.7 on 2022-03-14 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alloptionplay', '0009_auto_20220227_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='bottom_value',
            field=models.CharField(default='0', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='demandline_high',
            field=models.CharField(default='0', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='demandline_low',
            field=models.CharField(default='0', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='supplyline_high',
            field=models.CharField(default='0', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='supplyline_low',
            field=models.CharField(default='0', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='top_value',
            field=models.CharField(default='0', max_length=250, null=True),
        ),
    ]
